version: '3.1'

services:
  backend:
    build:
      context: .
    ports:
      - 8080:8080
    command: bash -c "
      python3 manage.py makemigrations
      && python3 manage.py migrate
      && gunicorn roof.wsgi -b 0.0.0.0:8080
      "
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - backend
    volumes:
      - ./static:/static